name: k2_connect_flutter
description: "The official Kopo Kopo K2 connect SDK"
version: 0.0.1
homepage: https://github.com/kopokopo/k2-connect-flutter
repository: https://github.com/kopokopo/k2-connect-flutter
issue_tracker: https://github.com/kopokopo/k2-connect-flutter/issues

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.5.1
  build_runner: ^2.4.6

flutter:
  assets:
    - assets/icons/
    - assets/logos/
